export * from './login/login.component'
export * from './home/home.component'
export * from './register/register.component'
export * from './admin/admin.component'
export * from './polytunnel/polytunnel.component'
export * from './plant/plant.component'
export * from './harvest/harvest.component'
// export * from './user-manage/user-manage.component'
// export * from './user-manage/user-manage.component'
// export * from './manage-sensors/manage-sensors.component'
// export * from './manage-green-house/manage-green-house.component'
// export * from './manage-contact/manage-contact.component'
// export * from './manage-plants/manage-plants.component'


